python enjoy.py \
    --env-name InmoovHandPlaceBulletEnvVision-v6 \
    --load-dir trained_models_0219_box_2_place_0220_3/ppo/ \
    --non-det 0 \
    --seed=1897 \
    --random_shape 0 \
    --random_size 1 \
    --default_box 1 \
    --up 1 \
    --renders 0 \
    --exclude_hard 0 
