python enjoy.py \
    --env-name InmoovHandPlaceBulletEnv-v8 \
    --load-dir trained_models_0302_cyl_4_place_0312_np_0/ppo/ \
    --non-det 0 \
    --seed=1898 \
    --random_shape 0 \
    --random_size 1 \
    --default_box 0 \
    --up 1 \
    --renders 0 \
    --exclude_hard 0 \
    --obs_noise 1 \
    --use_gt_6d 0 \
    --n_trials 1000