python enjoy.py \
    --env-name InmoovHandPlaceBulletEnv-v8 \
    --load-dir trained_models_0302_cyl_4_place_0307_2/ppo/ \
    --non-det 0 \
    --seed=1898 \
    --random_shape 0 \
    --random_size 1 \
    --default_box 0 \
    --up 1 \
    --renders 0 \
    --exclude_hard 0 \
    --vision_skip 2 \
    --control_skip 6 \
    --obs_noise 1 \
    --gen_vision_dataset 1 \
    --n_trials 1000
