python enjoy.py \
    --env-name InmoovHandPlaceBulletEnv-v7 \
    --load-dir trained_models_0302_box_20_place_0307_1/ppo/ \
    --non-det 0 \
    --seed=1898 \
    --random_shape 0 \
    --random_size 1 \
    --default_box 1 \
    --up 1 \
    --renders 0 \
    --exclude_hard 0  \
    --obs_noise 1 \
    --n_trials 200
